### ISSUE TITLE
Fork this project / no more maintained

### ISSUE THREAD

**Issue by MickL** [typicode/json-server#1219]
Hey @typicode , seems like this project is no more maintaiend? There are over 500 open issues and 72 pull requests. 

For example loading Typescript files instead of json (even tho this is named json-server) would be awesome! Open issue for 2,5 years: https://github.com/typicode/json-server/issues/833 and there is even a pull request for that: https://github.com/typicode/json-server/pull/994

If this project is actually no more maintained, may someone want to fork it? I really love how easy, fast and handy this is! Would love to see it beeing activly developed. There are so many PR's open right now but they dont get reviewed.

**Comment by SeeGreatness** [comment]
would love to see this get pulled from the grave!

**Comment by MickL** [comment]
Would love to see #938 too

**Comment by typicode** [comment]
Hey @MickL,

Personally, I'd love to release a 1.0 and I'm sorry for the lack of reply on issues.

The thing is that it's a bit complicated since I'm doing this on free time. In the past months, most of the work has gone in husky 5 and a new temporary license which I hope will help me in working on OSS a bit more (it's an experiment so I'll see how it goes).

If there's enough interest I may setup a goal on GitHub Sponsors to start working on v1 or at least a refresh of this project :)

**Comment by MickL** [comment]
Hey @typicode , nice to hear from you! The code seems kind of simple so contributing seems to be easy and I see a lot of contributions from the community. Anyhow pull requests need to be reviewed and merged but there are ones open for 5 years :/ So if at least could be done this would be super awesome!

For active development personally I would like to migrate to TypeScript and my number one feature requests ar being able to import ts files and the missing OR operator for filters. But as there are 500 open issues I would also check which one of them are highly requested/upvoted, give them a tag and then close all other ones with a bot if they dont have a tag and no one reacts to it anymore for X days.

**Comment by EdDeAlmeidaJr** [comment]
Would you consider passing the projet on to another maintainer?

**Comment by MickL** [comment]
One may just fork

**Comment by EdDeAlmeidaJr** [comment]
Yeah, I know. I already did it.  Enviado do Email para Windows 10 De: Mick LawitzkeEnviado:sexta-feira, 30 de julho de 2021 17:40Para: typicode/json-serverCc:Ed de Almeida; CommentAssunto: Re: [typicode/json-server] Fork this project / no more maintained (#1219) One may just fork—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TakerNezu** [comment]
Hi all.
I'm looking to use json-server and Frourio for smooth front-end and back-end development.
For my idea, it is a must that this nice project works with TypeScript.

Do you have a policy for this project yet?

I'm not good at English, but if there's anything I can do, I'd like to do it as much as I can.

**Comment by matiasperrone** [comment]
Try Mockoon

**Comment by SalahAdDin** [comment]
How is this going on?

**Comment by typicode** [comment]
> How is this going on?

I'm trying to improve funding so that working on it (and other Open Source projects) is more viable. Working on a new version by the way.

**Comment by platform-kit** [comment]
@typicode will the new version be released under this repo or another name?

Also, while we're at it, will you consider releasing under MIT License? It's very unclear what the legal and financial implications of the current license are.
