### ISSUE TITLE
DELETE call deletes all the entries.

### ISSUE THREAD

**Issue by injulkarnilesh** [typicode/json-server#13]
I am providing json file as a db source containing post elements as in : https://gist.github.com/injulkarnilesh/4cfd42501bfd5c13885f
Rest of the calls work fine
  GET /posts/ 
  GET /posts/3
  POST /posts/
These calls work as expected.

But on 
   DELETE /posts/3
Response says 
  Response does not contain any data.
with status 204.
and json data in the file gets emptied to 
{
  "posts": []
} 

Shouldn't it delete only the mentioned post rather than all the posts?

**Comment by aboudard** [comment]
Hello, just a quick note for anyone having such issues :
If you ever have an Entity `post` that uses an `id` field because json-server works by default with this name, AND you also have another `postId` field (reflecting you own future database), you will encounter the same "delete all" behavior. All you need to do is align the values of these 2 fields.

```json
{
    "id": 1,
    "postId": "PI524"
}
```
will be deleted every time, instead, align values :
```json
{
    "id": "PI524",
    "postId": "PI524"
}

**Comment by Mahmoudibrahim03** [comment]
> Hello, just a quick note for anyone having such issues : If you ever have an Entity `post` that uses an `id` field because json-server works by default with this name, AND you also have another `postId` field (reflecting you own future database), you will encounter the same "delete all" behavior. All you need to do is align the values of these 2 fields.
> 
> ```json
> {
>     "id": 1,
>     "postId": "PI524"
> }
> ```
> 
> will be deleted every time, instead, align values :
> 
> ```json
> {
>     "id": "PI524",
>     "postId": "PI524"
> }
> ```

<img width="610" alt="image" src="https://user-images.githubusercontent.com/16546001/212502682-91d3ee20-78bd-4d3b-b0c1-d9fd019a97ef.png">

what if I need to relate items like (questions - answers ) with form ID and each one should have its own id also @aboudard
