### ISSUE TITLE
POST request body can't add autogenerated attributes

### ISSUE THREAD

**Issue by sagufa2021** [typicode/json-server#1420]
I am using json-server library in my nodejs project to start a mocked server and perform POST operations. My request body doesn't have id, userId, and customerGuid which are all autogenerated fields. I tried to do this below but it only adds id and never adds userId and customerGuid.

Request body used for POST:

```
    {
    	"name": "Leon"
    	"qty": 3
    }

```
Response body received for POST above is:

```
    {
    	"name": "Leon",
    	"qty": 3,
        "id": 2
    }
```
Expected POST response body which i can't figure out why userId and customerGuid can't be added:

```
    {
    	"name": "Leon",
    	"qty": 3,
        "id" : 2,
        "userId": 37,
        "customerGuid": "af9a012b-faf2-4ef5-ae0c-51f945adff6c"
    }
```

Code in data.js:

   ```
 const faker = require('faker')
    
    let data = {
        user : []
    }
    
    data.user.push({
        id: faker.random.number({min:25,max:50}),     
        userId: faker.random.number({min:25,max:50}),
        customerGuid: faker.random.uuid(), 
        name: faker.company.companyName(),
        qty: faker.address.city()
    })
    
    
    module.exports = data
```

**Comment by MadhuSaini22** [comment]
@sagufa2021, The reason you are not getting the expected outcome in your POST response is likely due to the fact that json-server automatically generates an id field for you, but it doesn't handle additional custom fields like userId and customerGuid by default.

When json-server processes a POST request, it automatically assigns an id to the new record based on the existing data in the JSON file. However, for custom fields like userId and customerGuid, you need to handle their generation yourself.

In your case, you attempted to populate these fields in the data.js file, but json-server doesn't automatically use that data during POST requests. Instead, you need to create a custom route handler to handle the generation of these fields and update the response accordingly
