### ISSUE TITLE
q and other filters are mutually exclusive

### ISSUE THREAD

**Issue by fzaninotto** [typicode/json-server#145]
It seems that I can filter by property, and the result is a set of conditions combined unsing an AND logic. But the full-text query feature (using the `q` parameter) seems to add up as an OR condition. Illustrating my point using pseudo-SQL:

```

GET /post?title=foo&nbView=10
// something like SELECT * FROM post WHERE title='foo' AND nbView=10
GET /post?title=foo&nbView=10&q=bar
// something like SELECT * FROM post WHERE (title='foo' AND nbView=10) OR (fullTextIndex LIKE '%bar')
```

This is surprising: I would expect all filters to combine using an AND logic.

**Comment by typicode** [comment]
Good point, I'll fix that.
Thanks :+1:

**Comment by ryancrosser** [comment]
Just to add my two cents, I see these two operations as being mutually exclusive. There are performance benefits to keeping them them separate as the deepQuery operation a more expensive operation than simply finding an exact match within a property.
It might be a better compromise to implement a fuzzy match to the property search, something like ```/post?title=*foo``` or ```/post?title=fuzzy:foo```, wich would perform an ```indexOf()``` style comparision rather than ```===```.
Either way I would still keep ```q``` and the property searching separate.

**Comment by typicode** [comment]
@fzaninotto fixed in v0.7.22 ;)

@ryancrosser About fuzzy search, why not I'll check if there are  some modules for that. Don't really want to include custom code in JSON Server just for that or do something too complex. Also, search can be tricky `/post?title=*foo*bar`.

**Comment by fzaninotto** [comment]
Awesome, thanks a lot!

**Comment by typicode** [comment]
You're welcome :)
