### ISSUE TITLE
use newer version of lowdb ?

### ISSUE THREAD

**Issue by seriousme** [typicode/json-server#274]
Hi,

just installed json-server an I get an npm warning about lowdb depending on a deprecated version of graceful-fs (graceful-fs@3.0.8). I noticed that json-server is depending on lowdb 0.10.3 where the current lowdb 0.12.5 has been upgraded to use graceful-fs 4.1.3.

KR,
Hans

**Comment by typicode** [comment]
Hi @seriousme,

Thank you for the feedback.

I'm currently working on lowdb 0.13 (but it's not yet released). And since, there are breaking changes with 0.10 -> 0.12 and 0.12 -> 0.13, I'd rather release 0.13 then update code in JSON Server to avoid doing work twice.

That said, it's taking a little more time than expected to release 0.13, sorry for that.

**Comment by seriousme** [comment]
Not a problem :-)
Your upgrade strategy makes sense to me.
Thanks for the quick response !

**Comment by typicode** [comment]
Upgraded to `lowdb v0.13.0.beta-2` so there should be no warning now. Thanks again for the heads up.

When the documentation will be ready, I'll publish `lowdb v0.13.0` final release.

**Comment by desig2003** [comment]
Thank you for all your help cause I can get on the web do updates but all
those codes I'm clueless how did you see it and I didn't even know till I
got word from you do you work for work for Apple?

**Comment by paztis** [comment]
Hi again
Lowdb depependency is not to ^1.0.0 while you release a v2
Any update plan ?
