### ISSUE TITLE
can json-server return xml type?

### ISSUE THREAD

**Issue by fhefh2015** [typicode/json-server#281]

**Comment by typicode** [comment]
Yes, simply use the project as a module and modify `router.render` to output XML. If you look for json to xml on npm, you can find some libraries to help you convert data to XML.

You may need to test if data is an array though and put it into an object, since most converter requires objects to be passed.

```js
var jsonServer = require('json-server')
var server = jsonServer.create()
var router = jsonServer.router('db.json')
var middlewares = jsonServer.defaults()

server.use(middlewares)
server.use(router)

router.render = function (req, res) {
  var data = res.locals.data
  var str = convertDataToXML(data)
  res.send(str)
}

server.listen(3000, function () {
  console.log('JSON Server is running')
})
```

**Comment by niwang66** [comment]
Where is the code for "convertDataToXML"?
If I post an xml data, how to change the code?
