### ISSUE TITLE
id on POST

### ISSUE THREAD

**Issue by lioralt** [typicode/json-server#294]
Hi,
Why does an id string is added when i'm executing a post api toward the json-server ?
what is it for ? is it possible to disable this feature ?

thanks.

**Comment by typicode** [comment]
Hi,

In REST, when you POST to a resource list it creates an item and you can also get the full list of resources or just a single resource using the following URLs:

```sh
GET /photos
GET /photos/1
```

In order to be able to get photo `1`, there need to be an "identifier". This is why an `id` is added.
It's not possible to disable this feature.

**Comment by lioralt** [comment]
Thanks for explaining :+1:
