### ISSUE TITLE
Support `--middlewares` option

### ISSUE THREAD

**Issue by zakuro9715** [typicode/json-server#342]
Hi.

We can use express middlewares if use json-server as a module. But I want to specify middleware as cli option like this.

```
$ cat middlewares.js
module.exports = [require('my-auth-middleware'), require('my-limit-middleware')]
$ json-server db.json --middlewares=middlewares.js
```

I think it is very useful for guys not only me.

**Comment by christinerobinson426** [comment]
Ok

**Comment by typicode** [comment]
Hi @zakuro9715,

Thank you for the PR, I like the idea. Do you think it could be refactored so that the CLI can take `my-auth-middleware` and `my-limit-middleware` as individual arguments instead of just one file?

I guess that `yargs` should have some kind of option for this.

This way it could be possible to define them in the `json-server.json` config file:

```json
{
  "port": 3000,
  "middlewares": ["my-auth-middleware", "my-limit-middleware"]
}
```

**Comment by zakuro9715** [comment]
Hi @typicode.

I agree it and implemented it. Please see my PR!
