### ISSUE TITLE
Typo in documentation?

### ISSUE THREAD

**Issue by dschu-lab** [typicode/json-server#362]
The example for `Static file server` is confusing:
First a `public` folder is created. 

But later on, the server is started like this:
`json-server db.json --static ./static`

IMHO to be more consistend, this should be edited like this:
`json-server db.json --static ./public`

Or am I missing something?

**Comment by typicode** [comment]
Hi @dschu-lab,

Thank you for the feedback. Maybe the documentation is not clear enough :)

Actually, by __default__ `json-server` will serve files that are in `./public` directory if it exists. You don't have to pass an option for that.

But it's also possible to say use this `other-dir`: `json-server db.json --static ./other-dir`.
That's why in the `README` there's another dir that is passed to `--static`.

Suggestions to improve that in the README are welcome.

**Comment by typicode** [comment]
I've updated the README, hope it's clearer :)

**Comment by themre** [comment]
hm... i wanted to use this inside my create-react-app project and I put jsons inside mockapi folder. and if I type `json-server --watch db.json --static ./mockapi` it doesn't see any files. am I missing something?
