### ISSUE TITLE
Without data return

### ISSUE THREAD

**Issue by istommao** [typicode/json-server#384]
![image](https://cloud.githubusercontent.com/assets/5070879/19257717/681221f2-8fa4-11e6-843d-bcb5ec35ba8f.png)
![image](https://cloud.githubusercontent.com/assets/5070879/19257724/80108578-8fa4-11e6-86f1-e10532f405bf.png)

But success when url like this

![image](https://cloud.githubusercontent.com/assets/5070879/19257739/972b19ee-8fa4-11e6-93ea-d7e7964f17ca.png)
![image](https://cloud.githubusercontent.com/assets/5070879/19257745/a5f71630-8fa4-11e6-95bf-8153488576c1.png)

**Comment by typicode** [comment]
Hi @istommao,

`/` aren't supported in `db.json`, I would suggest having a look at:
https://github.com/typicode/json-server#add-routes
https://github.com/typicode/json-server#custom-output-example

You'll probably have to use the project as a module and add a rewrite rule to handle `/api` prefix, modify the output to add `previous`, `count`, `next` and `results`.

Also you'll have to tell JSON Server to use `uid` instead of `id` (`router.db._.id = 'uid'`).

These issues can help too:
https://github.com/typicode/json-server/issues/359
https://github.com/typicode/json-server/issues/382
https://github.com/typicode/json-server/issues/371

**Comment by istommao** [comment]
I see
thank a lots!

By the way

there is an error in README.md
![image](https://cloud.githubusercontent.com/assets/5070879/19263580/9997c530-8fcf-11e6-8fb7-8aab25c09204.png)

**res.Header is not a function**
![image](https://cloud.githubusercontent.com/assets/5070879/19263687/10995be4-8fd0-11e6-91cb-7fa565c4a048.png)

And i change res.Header to lowercase it works!
![image](https://cloud.githubusercontent.com/assets/5070879/19263700/240ddb82-8fd0-11e6-812c-471063647730.png)

**Comment by typicode** [comment]
Thank you for the heads-up! :)

**Comment by istommao** [comment]
You are welcome!
