### ISSUE TITLE
How to transform response body using CLI?

### ISSUE THREAD

**Issue by christophercr** [typicode/json-server#388]
Hi,

I'm checking out this library and is really easy to use! I've been able to run the server using the module approach (jsonServer router, middlewares, etc.).

However I'm trying to achieve the same thing using only the CLI, but I'm stuck trying to transform the response to add custom data to it. Using the module approach you can simply override the router.render method, but with the CLI, I can just provide middlewares but I can't transform the response in there.

Any ideas how I can achieve this?

**Comment by typicode** [comment]
Hi @christophercr,

Thanks for the feedback :)

I'd say it's not possible and not sure if it's something wished (i.e trying to make the CLI as flexible as Express code to save a few lines of code).

That would mean having either a `--renderer custom.js` option or having some kind of `json-server.config.js` where you would export an option object.

But the downside of a config file is that you need to learn to use it, instead of just using your existing Express knowledge.

**Comment by christophercr** [comment]
Alright, indeed it would add more complexity to the CLI and the learning curve would be even higher.
