### ISSUE TITLE
🐞 it seems that there is a bug ?

### ISSUE THREAD

**Issue by xgqfrms-GitHub** [typicode/json-server#513]
🐞 

> why this codes isn't a validate format ?

```json
"profile": { 
    "name": "typicode1",
    "name": "typicode2",
    "name": "typicode3"
}

```
>  only this format is OK (object in array)
```json
"profile": [
    { 
        "name": "typicode1"
    },
    { 
        "name": "typicode2"
    },
    { 
        "name": "typicode3"
    }
]
```

**Comment by arthrmlo** [comment]
In the first sample, you are declaring a single object `profile` with 3 key-value pairs `name`. Although it is a valid JSON format, a parser _may_ complain about colliding keys (Which I guess the json-server parser does, and that's why you're asking).

The second sample works because you are declaring an array of objects, and they have their own "space" (Delimited by the `{ ... }`). This means that you can have repeated identifier keys, as long as they are in their own namespace, and they don't collide within themselves.

For instance:
~~~~
{
  "someObject": {
    "property": "A",
    "property": "B"  // <--- Collision
  }
}
~~~~
There's a collision on the `property` key.

Using an array:
~~~~
{
  "someArray": [
    { "name": "A", "value": "1" },
    { "name": "A", "value": "2" }, // <-- Repeated names property, but valid!
    { "name": "B", "value": "3", "value": "4" } // <-- Collision
  ]
}
~~~~
There's a collision in the property `value` on the third object`B`. 

If you want to validate your code, I recommend using some online linter like [this one](http://jsonlint.com/).

More info on the subject: http://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object

**Comment by xgqfrms-GitHub** [comment]
### 😄  Thanks for your time! 👍 

This is a very good explanation!


However, I still have some confused, could you give more explain?

> db.json

```json
{
    "profile": {
        "name1": "typicode1",
        "name2": "typicode2",
        "name3": "typicode3"
    },
    "employess": [
        {
            "id": 0,
            "firstName": "Jaiden",
            "lastName": "Williamson",
            "email": "Kiera.Prosacco70@hotmail.com"
        },
        {
            "id": 1,
            "firstName": "Elody",
            "lastName": "Leuschke",
            "email": "Ena_Beier22@gmail.com"
        }
    ]
}
``` 

> http://localhost:3000/profile?q=typicode2

```sh
{
    "name1": "typicode1",
    "name2": "typicode2",
    "name3": "typicode3"
}
```
How can I get this result ?

> http://localhost:3000/profile?q=typicode2

```sh
{
    "name2": "typicode2"
}
```

**Comment by arthrmlo** [comment]
You can use 3 methods to access your object: directly by key, using  Querystring or by key/param.

Direct access:
~~~~
{
  "typicode1": {
    "name": "typicode1"
  },
  "typicode2": {
    "name": "typicode2"
  },
  "typicode3": {
    "name": "typicode3"
  }
}
~~~~
Query: `IP:PORT/typicode1`, returns the object directly.

Using querystring:
~~~~
{
  "names": [
    { "name": "typicode1" },
    { "name": "typicode1" }, // <-- Will return 2 object entries
    { "name": "typicode2" },
    { "name": "typicode3" }
  ]
}
~~~~
Query: `IP:PORT/names?q=typicode1`, returns an array with the results.

Key/parameter:
~~~~
{
  "names": [
    { "id": 1, "name": "typicode1" },
    { "id": 2, "name": "typicode2" },
    { "id": 3, "name": "typicode3" },
    { "id": 3, "name": "typicode4" } // <-- Wont be printed, unless queried with querystring.
  ]
}
~~~~
Query: `IP:PORT/names/1`, returns the object with id 1 (Primary key). Note that `/names/3` will return only the first entry (Duplicated primary keys).

I recommend using the third one, as it is easier to read and is widely used (As an example, [Github API](https://developer.github.com/v3/#schema). [They use the username as the primary key for queries, instead of id. Your profile: [here](https://api.github.com/users/xgqfrms-GitHub)]).

JSON-Server implements all the HTTP verbs, so you can automatically GET/POST/PUT/DELETE values. There are also extra functionalities like filter, paginate, sort... the documentation is on the home page of the project. 

Just remember that this is a fake service, use this project just as a reference for implementing your REST endpoints with a proper backend later on.

**Comment by xgqfrms-GitHub** [comment]
Thanks a lot, again!
