### ISSUE TITLE
custom routes not working

### ISSUE THREAD

**Issue by elowes** [typicode/json-server#540]
I add routes.json like this.
``` js
{
  "/stock?key=:key": "/:key"
}
```
then I open `/stock?key=title`, but not get data from `/title`, what should I do?

**Comment by OneNewLife** [comment]
To add rewrite rules, use `jsonServer.rewriter()`:

``` javascript
// Add this before server.use(router)
server.use(jsonServer.rewriter({
  "/stock?key=:key": "/:key"
}))
```

instead of adding `routes.json`, `json-server` just read data from `json`, rewrite rules should be written in config

**Comment by bduff9** [comment]
I need this as well.  Are you saying using a custom routes file is not supported?  If so, that should be removed from the docs as it clearly indicates it should work but it doesn't seem to.  I do get a log output that says my custom route is available but then I just get a 404 when trying to use it.  If this should work, then I need help in figuring out where I went wrong.  Otherwise, the docs should be amended.

**Comment by BrennerSpear** [comment]
the custom route is for ```stock```. Anything after the ```?``` is put into the query.

How about ``` "/stock/key/:key": "/:key"``` ?

**Comment by bduff9** [comment]
Yes, that would be great if it worked that way.  However, from my testing and from other issues on here, right now the query string is lost when redirecting.  If it wasn't, then this would be less of an issue.  I also never got the routes.json file to work as it never redirected.  However, I did have more success with the rewriter (albeit still with no query string)

**Comment by BrennerSpear** [comment]
what do you mean the query string is lost?

**Comment by bduff9** [comment]
Hmm, OK so I may be getting my wires crossed now with these two tickets.  I just tried a brand new example with a very basic setup and it does work correctly as I would expect it to.  Let me stop replying here as my issue is the actual problem I am running into.

**Comment by elowes** [comment]
thx
