### ISSUE TITLE
Json-server and lowdb

### ISSUE THREAD

**Issue by Shuunen** [typicode/json-server#65]
Hey again :)

I'm working on https://github.com/Shuunen/pracker

The aim of this tool is to watch a product price on the web and update a UI to alert the user when a product price changed.

So I use lowdb and json-server on the same file and you can see my implementation here : https://github.com/Shuunen/pracker/blob/master/pracker.js

On line 51 I added a "foo bar" test : product.toto = 42;

By db.json file is never updated with this.

But, if I comment the //Server init :
```
// Server
var jsonServer = require('json-server');
var router = jsonServer.router(dbFile);
var server = jsonServer.create();
server.use(jsonServer.defaults);
server.use(router);
server.listen(3000);
```
I will find my product.toto = 42 in db.json

So I think json-server is locking the file and prevent lowdb from updating, right ?

**Comment by typicode** [comment]
The reason is a little more tricky.

Actually, when you directly modify an object in lowdb, it has no way to know it so you need to call `.save()`
There was a similar issue a few days ago: https://github.com/typicode/lowdb/issues/39

Also, having two instances writing on the same file will result in bugs.
To have one instance of lowdb, you can retrieve it from the router:

```javascript
var low = require('lowdb')
low.mixin(require('underscore-db'))

// ...

var router = jsonServer.router(dbFile)
var db = router.db
```

**Comment by Shuunen** [comment]
I'm on it :)

Thanks for your fast support :+1:

**Comment by typicode** [comment]
Great :+1:

**Comment by samuelnata-via** [comment]
Current working verssion is:
`var router = jsonServer.router("MyDbFile.json")
var db = router.db
low.mixin(require('underscore-db'))`
