### ISSUE TITLE
Can I write to the db within a middleware?

### ISSUE THREAD

**Issue by aalbericio** [typicode/json-server#675]
I need to intercept and write something to the db in some special routes inside a middleware.

Does json-server support this? Is there an example?

Thanks in advance.

**Comment by aalbericio** [comment]
Well, I don't know if it's the most beautiful way to do it but having this inside the middleware's module.exports works for me:

const jsonServer = require('json-server')
const router = jsonServer.router('json-server-db.json');
const db = router.db;
...
db.write()
...

**Comment by paztis** [comment]
In case we've got a server run through cli, if we do this in the middleware, we create another router
If the 2nd router (middleware one) change the db, the cli server detect a change and restarts itself.

This can generates cash in chained request
Inside a middleware, we need to be able to access the existing router instead of creating another instance.

Any idea ?

**Comment by paztis** [comment]
ok find the real way for this
inside the middleware, is is available in req.app.db
```

const middleware = async (req, res, next) => {
    console.log('db', req.app.db)

```
